(part "MICROFJ-30035-TSV-TR"
    (packageRef "MICROFJ30035TSVTR")
    (interface
        (port "A1" (symbPinId 1) (portName "CATHODE_1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "NO_CONNECT_1") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "NO_CONNECT_2") (portType INOUT))
        (port "B1" (symbPinId 4) (portName "ANODE") (portType INOUT))
        (port "B3" (symbPinId 5) (portName "FAST_OUTPUT") (portType INOUT))
        (port "C1" (symbPinId 6) (portName "NO_CONNECT_3") (portType INOUT))
        (port "C2" (symbPinId 7) (portName "NO_CONNECT_4") (portType INOUT))
        (port "C3" (symbPinId 8) (portName "CATHODE_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "MICROFJ-30035-TSV-TR")
    (property "Mouser_Part_Number" "863-MFJ30035TSVTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/MICROFJ-30035-TSV-TR?qs=byeeYqUIh0NWig1VlbDyxw%3D%3D")
    (property "Arrow_Part_Number" "MICROFJ-30035-TSV-TR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/microfj-30035-tsv-tr/on-semiconductor?region=nac")
    (property "Description" "High-density microcells; Optimized for high-performance timing applications, such as ToF-PET; Ultra-low dark count rates of 50 kHz/mm2 typical; J-Series sensors feature ON Semiconductor's unique 'fast output' terminal; Exceptional breakdown voltage uniformity of +/-250 mV; Temperature stability of 21.5 mV/C; 3 mm, 4 mm and 6 mm sensor sizes; Available in a reflow solder compatible TSV chip-scale package; Bias voltage of <30 V")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/MICROJ-SERIES-D.PDF")
    (property "symbolName1" "MICROFJ-30035-TSV-TR")
)
